import type { Exercise } from '../models/types';

export const EXERCISES: Exercise[] = [
  // === KLATKA PIERSIOWA ===
  {
    id: 'push-up',
    name: { pl: 'Pompki', de: 'Liegestütze', en: 'Push-ups' },
    description: {
      pl: 'Klasyczne pompki — podstawowe ćwiczenie na klatkę piersiową i tricepsy.',
      de: 'Klassische Liegestütze — Grundübung für Brust und Trizeps.',
      en: 'Classic push-ups — fundamental chest and triceps exercise.',
    },
    category: 'chest',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: [],
    instructions: {
      pl: ['Ułóż dłonie na szerokość barków', 'Utrzymuj proste ciało', 'Opuść klatkę do podłogi', 'Wypchnij się do góry'],
      de: ['Hände schulterbreit aufstellen', 'Körper gerade halten', 'Brust zum Boden senken', 'Nach oben drücken'],
      en: ['Place hands shoulder-width apart', 'Keep body straight', 'Lower chest to floor', 'Push back up'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },
  {
    id: 'diamond-push-up',
    name: { pl: 'Pompki diamentowe', de: 'Diamant-Liegestütze', en: 'Diamond Push-ups' },
    description: {
      pl: 'Pompki z wąskim chwytem — nacisk na tricepsy i środkową część klatki.',
      de: 'Liegestütze mit engem Griff — Fokus auf Trizeps und innere Brust.',
      en: 'Narrow grip push-ups — emphasis on triceps and inner chest.',
    },
    category: 'chest',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'triceps'],
    equipment: [],
    instructions: {
      pl: ['Ułóż dłonie w kształt diamentu', 'Łokcie blisko ciała', 'Opuść się powoli', 'Wypchnij dynamicznie'],
      de: ['Hände in Diamantform positionieren', 'Ellbogen nah am Körper', 'Langsam absenken', 'Dynamisch hochdrücken'],
      en: ['Form diamond shape with hands', 'Keep elbows close', 'Lower slowly', 'Push up explosively'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 8,
  },

  // === PLECY ===
  {
    id: 'superman',
    name: { pl: 'Superman', de: 'Superman', en: 'Superman' },
    description: {
      pl: 'Unoszenie ramion i nóg w leżeniu przodem — wzmacnia dolne plecy.',
      de: 'Arme und Beine in Bauchlage heben — stärkt den unteren Rücken.',
      en: 'Lying face down, raise arms and legs — strengthens lower back.',
    },
    category: 'back',
    difficulty: 'beginner',
    muscleGroups: ['lower back', 'glutes'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na brzuchu', 'Wyciągnij ręce do przodu', 'Unieś ręce i nogi jednocześnie', 'Przytrzymaj 2-3 sekundy'],
      de: ['Auf den Bauch legen', 'Arme nach vorne strecken', 'Arme und Beine gleichzeitig heben', '2-3 Sekunden halten'],
      en: ['Lie face down', 'Extend arms forward', 'Raise arms and legs simultaneously', 'Hold 2-3 seconds'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 5,
  },
  {
    id: 'inverted-row',
    name: { pl: 'Wiosłowanie odwrócone', de: 'Invertiertes Rudern', en: 'Inverted Row' },
    description: {
      pl: 'Wiosłowanie ciałem pod drążkiem lub stołem — świetne na plecy.',
      de: 'Rudern unter einer Stange oder einem Tisch — großartig für den Rücken.',
      en: 'Rowing under a bar or table — great for back muscles.',
    },
    category: 'back',
    difficulty: 'intermediate',
    muscleGroups: ['upper back', 'biceps', 'rear delts'],
    equipment: ['bar'],
    instructions: {
      pl: ['Chwyć drążek na wysokości bioder', 'Ciało proste jak deska', 'Podciągnij klatkę do drążka', 'Opuść się kontrolowanie'],
      de: ['Stange auf Hüfthöhe greifen', 'Körper gerade wie ein Brett', 'Brust zur Stange ziehen', 'Kontrolliert absenken'],
      en: ['Grip bar at hip height', 'Keep body straight', 'Pull chest to bar', 'Lower with control'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 6,
  },

  // === NOGI ===
  {
    id: 'squat',
    name: { pl: 'Przysiady', de: 'Kniebeugen', en: 'Squats' },
    description: {
      pl: 'Klasyczne przysiady — król ćwiczeń na nogi.',
      de: 'Klassische Kniebeugen — König der Beinübungen.',
      en: 'Classic squats — the king of leg exercises.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: [],
    instructions: {
      pl: ['Stopy na szerokość bioder', 'Biodra cofnij do tyłu', 'Kolana nie wychodzą za palce', 'Zejdź do kąta 90°'],
      de: ['Füße hüftbreit aufstellen', 'Hüfte nach hinten schieben', 'Knie nicht über die Zehen', 'Bis 90° Winkel senken'],
      en: ['Feet hip-width apart', 'Push hips back', 'Knees don\'t pass toes', 'Lower to 90 degrees'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 8,
  },
  {
    id: 'lunge',
    name: { pl: 'Wykroki', de: 'Ausfallschritte', en: 'Lunges' },
    description: {
      pl: 'Wykroki do przodu — wzmacniają nogi i poprawiają równowagę.',
      de: 'Ausfallschritte nach vorne — stärken die Beine und verbessern die Balance.',
      en: 'Forward lunges — strengthen legs and improve balance.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: [],
    instructions: {
      pl: ['Zrób duży krok do przodu', 'Tylne kolano prawie dotyka podłogi', 'Przednie kolano nad stopą', 'Wróć do pozycji wyjściowej'],
      de: ['Großen Schritt nach vorne', 'Hinteres Knie fast zum Boden', 'Vorderes Knie über dem Fuß', 'Zurück in Ausgangsposition'],
      en: ['Take a big step forward', 'Back knee almost touches floor', 'Front knee over foot', 'Return to starting position'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },
  {
    id: 'jump-squat',
    name: { pl: 'Przysiady z wyskokiem', de: 'Sprung-Kniebeugen', en: 'Jump Squats' },
    description: {
      pl: 'Przysiady z dynamicznym wyskokiem — budują siłę eksplozywną.',
      de: 'Kniebeugen mit dynamischem Sprung — bauen Explosivkraft auf.',
      en: 'Squats with explosive jump — build explosive power.',
    },
    category: 'legs',
    difficulty: 'intermediate',
    muscleGroups: ['quads', 'glutes', 'calves'],
    equipment: [],
    instructions: {
      pl: ['Wykonaj przysiad', 'Wyskocz dynamicznie w górę', 'Ląduj miękko na palcach', 'Natychmiast przejdź do kolejnego'],
      de: ['Kniebeuge ausführen', 'Dynamisch nach oben springen', 'Weich auf den Zehen landen', 'Sofort zur nächsten übergehen'],
      en: ['Perform a squat', 'Jump explosively upward', 'Land softly on toes', 'Immediately transition to next'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 10,
  },

  // === BARKI ===
  {
    id: 'pike-push-up',
    name: { pl: 'Pompki w szczycie', de: 'Pike-Liegestütze', en: 'Pike Push-ups' },
    description: {
      pl: 'Pompki z uniesionymi biodrami — nacisk na barki.',
      de: 'Liegestütze mit erhöhter Hüfte — Fokus auf Schultern.',
      en: 'Push-ups with elevated hips — shoulder focused.',
    },
    category: 'shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: [],
    instructions: {
      pl: ['Ustaw się w pozycji V', 'Biodra wysoko', 'Opuść głowę w kierunku podłogi', 'Wypchnij się do góry'],
      de: ['In V-Position aufstellen', 'Hüfte hoch', 'Kopf Richtung Boden senken', 'Nach oben drücken'],
      en: ['Set up in V position', 'Hips high', 'Lower head toward floor', 'Push back up'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },

  // === RAMIONA ===
  {
    id: 'tricep-dip',
    name: { pl: 'Dipy na triceps', de: 'Trizeps-Dips', en: 'Tricep Dips' },
    description: {
      pl: 'Prostowania na ławce lub krześle — izolacja tricepsów.',
      de: 'Dips an Bank oder Stuhl — Trizeps-Isolation.',
      en: 'Dips on bench or chair — triceps isolation.',
    },
    category: 'arms',
    difficulty: 'beginner',
    muscleGroups: ['triceps', 'shoulders'],
    equipment: ['bench'],
    instructions: {
      pl: ['Oprzyj ręce na krawędzi', 'Nogi wyciągnięte do przodu', 'Opuść biodra w dół', 'Wypchnij się ramionami'],
      de: ['Hände auf die Kante stützen', 'Beine nach vorne strecken', 'Hüfte nach unten senken', 'Mit den Armen hochdrücken'],
      en: ['Place hands on edge', 'Legs extended forward', 'Lower hips down', 'Push up with arms'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 6,
  },

  // === BRZUCH ===
  {
    id: 'plank',
    name: { pl: 'Plank (deska)', de: 'Plank (Brett)', en: 'Plank' },
    description: {
      pl: 'Izometryczne ćwiczenie na core — fundament stabilizacji.',
      de: 'Isometrische Core-Übung — Grundlage der Stabilisation.',
      en: 'Isometric core exercise — foundation of stabilization.',
    },
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ['core', 'shoulders', 'lower back'],
    equipment: [],
    instructions: {
      pl: ['Oprzyj się na przedramionach', 'Ciało proste jak deska', 'Napnij brzuch i pośladki', 'Utrzymaj pozycję'],
      de: ['Auf Unterarme stützen', 'Körper gerade wie ein Brett', 'Bauch und Gesäß anspannen', 'Position halten'],
      en: ['Rest on forearms', 'Body straight like a board', 'Tighten abs and glutes', 'Hold position'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 5,
  },
  {
    id: 'bicycle-crunch',
    name: { pl: 'Brzuszki rowerowe', de: 'Fahrrad-Crunches', en: 'Bicycle Crunches' },
    description: {
      pl: 'Skręty z uniesieniem nóg — intensywna praca skośnych mięśni brzucha.',
      de: 'Drehungen mit angehobenen Beinen — intensive schräge Bauchmuskelarbeit.',
      en: 'Twisting with raised legs — intense oblique work.',
    },
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'obliques'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na plecach', 'Ręce za głową', 'Łokieć do przeciwnego kolana', 'Naprzemienne ruchy nóg'],
      de: ['Auf den Rücken legen', 'Hände hinter den Kopf', 'Ellbogen zum gegenüberliegenden Knie', 'Abwechselnde Beinbewegungen'],
      en: ['Lie on your back', 'Hands behind head', 'Elbow to opposite knee', 'Alternating leg movements'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 7,
  },

  // === KARDIO ===
  {
    id: 'burpee',
    name: { pl: 'Burpees', de: 'Burpees', en: 'Burpees' },
    description: {
      pl: 'Kompleksowe ćwiczenie całego ciała — kardio + siła.',
      de: 'Komplexe Ganzkörperübung — Kardio + Kraft.',
      en: 'Complex full-body exercise — cardio + strength.',
    },
    category: 'cardio',
    difficulty: 'advanced',
    muscleGroups: ['full body'],
    equipment: [],
    instructions: {
      pl: ['Przysiad → ręce na podłogę', 'Wyrzuć nogi do tyłu (pozycja pompki)', 'Pompka', 'Podciągnij nogi i wyskocz w górę'],
      de: ['Kniebeuge → Hände auf den Boden', 'Beine nach hinten werfen (Liegestützposition)', 'Liegestütz', 'Beine anziehen und nach oben springen'],
      en: ['Squat → hands on floor', 'Jump feet back (plank position)', 'Push-up', 'Jump feet in and jump up'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 12,
  },
  {
    id: 'jumping-jack',
    name: { pl: 'Pajacyki', de: 'Hampelmänner', en: 'Jumping Jacks' },
    description: {
      pl: 'Klasyczne pajacyki — rozgrzewka i kardio.',
      de: 'Klassische Hampelmänner — Aufwärmung und Kardio.',
      en: 'Classic jumping jacks — warm-up and cardio.',
    },
    category: 'cardio',
    difficulty: 'beginner',
    muscleGroups: ['full body'],
    equipment: [],
    instructions: {
      pl: ['Stój prosto, ręce wzdłuż ciała', 'Wyskocz rozkładając nogi i ręce', 'Wróć do pozycji wyjściowej', 'Powtarzaj dynamicznie'],
      de: ['Gerade stehen, Arme am Körper', 'Springen mit Beinen und Armen auseinander', 'Zurück in Ausgangsposition', 'Dynamisch wiederholen'],
      en: ['Stand straight, arms at sides', 'Jump spreading legs and arms', 'Return to starting position', 'Repeat dynamically'],
    },
    durationSeconds: 60,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 8,
  },
  {
    id: 'mountain-climber',
    name: { pl: 'Wspinaczka górska', de: 'Bergsteiger', en: 'Mountain Climbers' },
    description: {
      pl: 'Dynamiczne podciąganie kolan w pozycji pompki — kardio + core.',
      de: 'Dynamisches Knieanziehen in Liegestützposition — Kardio + Core.',
      en: 'Dynamic knee drives in plank position — cardio + core.',
    },
    category: 'cardio',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'shoulders', 'quads'],
    equipment: [],
    instructions: {
      pl: ['Pozycja pompki', 'Podciągnij kolano do klatki', 'Zmień nogę dynamicznie', 'Utrzymuj szybkie tempo'],
      de: ['Liegestützposition', 'Knie zur Brust ziehen', 'Dynamisch Bein wechseln', 'Schnelles Tempo halten'],
      en: ['Plank position', 'Drive knee to chest', 'Switch legs dynamically', 'Keep fast pace'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 11,
  },

  // === ROZCIĄGANIE ===
  {
    id: 'standing-quad-stretch',
    name: { pl: 'Rozciąganie czworogłowego', de: 'Quadrizeps-Dehnung', en: 'Standing Quad Stretch' },
    description: {
      pl: 'Rozciąganie przedniego uda w pozycji stojącej.',
      de: 'Dehnung des vorderen Oberschenkels im Stehen.',
      en: 'Standing front thigh stretch.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['quads'],
    equipment: [],
    instructions: {
      pl: ['Stań na jednej nodze', 'Chwyć stopę drugiej nogi za plecami', 'Przyciągnij piętę do pośladka', 'Przytrzymaj 20-30 sekund'],
      de: ['Auf einem Bein stehen', 'Fuß des anderen Beins hinter dem Rücken greifen', 'Ferse zum Gesäß ziehen', '20-30 Sekunden halten'],
      en: ['Stand on one leg', 'Grab foot of other leg behind back', 'Pull heel to glute', 'Hold 20-30 seconds'],
    },
    durationSeconds: 30,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },
  {
    id: 'childs-pose',
    name: { pl: 'Pozycja dziecka', de: 'Kindeshaltung', en: 'Child\'s Pose' },
    description: {
      pl: 'Pozycja relaksacyjna rozciągająca plecy i ramiona.',
      de: 'Entspannungsposition für Rücken und Schultern.',
      en: 'Relaxation pose stretching back and shoulders.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['back', 'shoulders', 'hips'],
    equipment: [],
    instructions: {
      pl: ['Uklęknij i usiądź na piętach', 'Wyciągnij ręce do przodu', 'Czoło na podłodze', 'Oddychaj głęboko, przytrzymaj 30-60s'],
      de: ['Knien und auf die Fersen setzen', 'Arme nach vorne strecken', 'Stirn auf den Boden', 'Tief atmen, 30-60s halten'],
      en: ['Kneel and sit on heels', 'Extend arms forward', 'Forehead on floor', 'Breathe deeply, hold 30-60s'],
    },
    durationSeconds: 45,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },
];
