import type { Exercise } from '../models/types';

export const EXERCISES: Exercise[] = [
  // === KLATKA PIERSIOWA ===
  {
    id: 'push-up',
    name: { pl: 'Pompki', de: 'Liegestütze', en: 'Push-ups' },
    description: {
      pl: 'Klasyczne pompki — podstawowe ćwiczenie na klatkę piersiową i tricepsy.',
      de: 'Klassische Liegestütze — Grundübung für Brust und Trizeps.',
      en: 'Classic push-ups — fundamental chest and triceps exercise.',
    },
    category: 'chest',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: [],
    instructions: {
      pl: ['Ułóż dłonie na szerokość barków', 'Utrzymuj proste ciało', 'Opuść klatkę do podłogi', 'Wypchnij się do góry'],
      de: ['Hände schulterbreit aufstellen', 'Körper gerade halten', 'Brust zum Boden senken', 'Nach oben drücken'],
      en: ['Place hands shoulder-width apart', 'Keep body straight', 'Lower chest to floor', 'Push back up'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },
  {
    id: 'diamond-push-up',
    name: { pl: 'Pompki diamentowe', de: 'Diamant-Liegestütze', en: 'Diamond Push-ups' },
    description: {
      pl: 'Pompki z wąskim chwytem — nacisk na tricepsy i środkową część klatki.',
      de: 'Liegestütze mit engem Griff — Fokus auf Trizeps und innere Brust.',
      en: 'Narrow grip push-ups — emphasis on triceps and inner chest.',
    },
    category: 'chest',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'triceps'],
    equipment: [],
    instructions: {
      pl: ['Ułóż dłonie w kształt diamentu', 'Łokcie blisko ciała', 'Opuść się powoli', 'Wypchnij dynamicznie'],
      de: ['Hände in Diamantform positionieren', 'Ellbogen nah am Körper', 'Langsam absenken', 'Dynamisch hochdrücken'],
      en: ['Form diamond shape with hands', 'Keep elbows close', 'Lower slowly', 'Push up explosively'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 8,
  },

  // === PLECY ===
  {
    id: 'superman',
    name: { pl: 'Superman', de: 'Superman', en: 'Superman' },
    description: {
      pl: 'Unoszenie ramion i nóg w leżeniu przodem — wzmacnia dolne plecy.',
      de: 'Arme und Beine in Bauchlage heben — stärkt den unteren Rücken.',
      en: 'Lying face down, raise arms and legs — strengthens lower back.',
    },
    category: 'back',
    difficulty: 'beginner',
    muscleGroups: ['lower back', 'glutes'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na brzuchu', 'Wyciągnij ręce do przodu', 'Unieś ręce i nogi jednocześnie', 'Przytrzymaj 2-3 sekundy'],
      de: ['Auf den Bauch legen', 'Arme nach vorne strecken', 'Arme und Beine gleichzeitig heben', '2-3 Sekunden halten'],
      en: ['Lie face down', 'Extend arms forward', 'Raise arms and legs simultaneously', 'Hold 2-3 seconds'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 5,
  },
  {
    id: 'inverted-row',
    name: { pl: 'Wiosłowanie odwrócone', de: 'Invertiertes Rudern', en: 'Inverted Row' },
    description: {
      pl: 'Wiosłowanie ciałem pod drążkiem lub stołem — świetne na plecy.',
      de: 'Rudern unter einer Stange oder einem Tisch — großartig für den Rücken.',
      en: 'Rowing under a bar or table — great for back muscles.',
    },
    category: 'back',
    difficulty: 'intermediate',
    muscleGroups: ['upper back', 'biceps', 'rear delts'],
    equipment: ['bar'],
    instructions: {
      pl: ['Chwyć drążek na wysokości bioder', 'Ciało proste jak deska', 'Podciągnij klatkę do drążka', 'Opuść się kontrolowanie'],
      de: ['Stange auf Hüfthöhe greifen', 'Körper gerade wie ein Brett', 'Brust zur Stange ziehen', 'Kontrolliert absenken'],
      en: ['Grip bar at hip height', 'Keep body straight', 'Pull chest to bar', 'Lower with control'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 6,
  },

  // === NOGI ===
  {
    id: 'squat',
    name: { pl: 'Przysiady', de: 'Kniebeugen', en: 'Squats' },
    description: {
      pl: 'Klasyczne przysiady — król ćwiczeń na nogi.',
      de: 'Klassische Kniebeugen — König der Beinübungen.',
      en: 'Classic squats — the king of leg exercises.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: [],
    instructions: {
      pl: ['Stopy na szerokość bioder', 'Biodra cofnij do tyłu', 'Kolana nie wychodzą za palce', 'Zejdź do kąta 90°'],
      de: ['Füße hüftbreit aufstellen', 'Hüfte nach hinten schieben', 'Knie nicht über die Zehen', 'Bis 90° Winkel senken'],
      en: ['Feet hip-width apart', 'Push hips back', 'Knees don\'t pass toes', 'Lower to 90 degrees'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 8,
  },
  {
    id: 'lunge',
    name: { pl: 'Wykroki', de: 'Ausfallschritte', en: 'Lunges' },
    description: {
      pl: 'Wykroki do przodu — wzmacniają nogi i poprawiają równowagę.',
      de: 'Ausfallschritte nach vorne — stärken die Beine und verbessern die Balance.',
      en: 'Forward lunges — strengthen legs and improve balance.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: [],
    instructions: {
      pl: ['Zrób duży krok do przodu', 'Tylne kolano prawie dotyka podłogi', 'Przednie kolano nad stopą', 'Wróć do pozycji wyjściowej'],
      de: ['Großen Schritt nach vorne', 'Hinteres Knie fast zum Boden', 'Vorderes Knie über dem Fuß', 'Zurück in Ausgangsposition'],
      en: ['Take a big step forward', 'Back knee almost touches floor', 'Front knee over foot', 'Return to starting position'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },
  {
    id: 'jump-squat',
    name: { pl: 'Przysiady z wyskokiem', de: 'Sprung-Kniebeugen', en: 'Jump Squats' },
    description: {
      pl: 'Przysiady z dynamicznym wyskokiem — budują siłę eksplozywną.',
      de: 'Kniebeugen mit dynamischem Sprung — bauen Explosivkraft auf.',
      en: 'Squats with explosive jump — build explosive power.',
    },
    category: 'legs',
    difficulty: 'intermediate',
    muscleGroups: ['quads', 'glutes', 'calves'],
    equipment: [],
    instructions: {
      pl: ['Wykonaj przysiad', 'Wyskocz dynamicznie w górę', 'Ląduj miękko na palcach', 'Natychmiast przejdź do kolejnego'],
      de: ['Kniebeuge ausführen', 'Dynamisch nach oben springen', 'Weich auf den Zehen landen', 'Sofort zur nächsten übergehen'],
      en: ['Perform a squat', 'Jump explosively upward', 'Land softly on toes', 'Immediately transition to next'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 10,
  },

  // === BARKI ===
  {
    id: 'pike-push-up',
    name: { pl: 'Pompki w szczycie', de: 'Pike-Liegestütze', en: 'Pike Push-ups' },
    description: {
      pl: 'Pompki z uniesionymi biodrami — nacisk na barki.',
      de: 'Liegestütze mit erhöhter Hüfte — Fokus auf Schultern.',
      en: 'Push-ups with elevated hips — shoulder focused.',
    },
    category: 'shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: [],
    instructions: {
      pl: ['Ustaw się w pozycji V', 'Biodra wysoko', 'Opuść głowę w kierunku podłogi', 'Wypchnij się do góry'],
      de: ['In V-Position aufstellen', 'Hüfte hoch', 'Kopf Richtung Boden senken', 'Nach oben drücken'],
      en: ['Set up in V position', 'Hips high', 'Lower head toward floor', 'Push back up'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },

  // === RAMIONA ===
  {
    id: 'tricep-dip',
    name: { pl: 'Dipy na triceps', de: 'Trizeps-Dips', en: 'Tricep Dips' },
    description: {
      pl: 'Prostowania na ławce lub krześle — izolacja tricepsów.',
      de: 'Dips an Bank oder Stuhl — Trizeps-Isolation.',
      en: 'Dips on bench or chair — triceps isolation.',
    },
    category: 'arms',
    difficulty: 'beginner',
    muscleGroups: ['triceps', 'shoulders'],
    equipment: ['bench'],
    instructions: {
      pl: ['Oprzyj ręce na krawędzi', 'Nogi wyciągnięte do przodu', 'Opuść biodra w dół', 'Wypchnij się ramionami'],
      de: ['Hände auf die Kante stützen', 'Beine nach vorne strecken', 'Hüfte nach unten senken', 'Mit den Armen hochdrücken'],
      en: ['Place hands on edge', 'Legs extended forward', 'Lower hips down', 'Push up with arms'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 6,
  },

  // === BRZUCH ===
  {
    id: 'plank',
    name: { pl: 'Plank (deska)', de: 'Plank (Brett)', en: 'Plank' },
    description: {
      pl: 'Izometryczne ćwiczenie na core — fundament stabilizacji.',
      de: 'Isometrische Core-Übung — Grundlage der Stabilisation.',
      en: 'Isometric core exercise — foundation of stabilization.',
    },
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ['core', 'shoulders', 'lower back'],
    equipment: [],
    instructions: {
      pl: ['Oprzyj się na przedramionach', 'Ciało proste jak deska', 'Napnij brzuch i pośladki', 'Utrzymaj pozycję'],
      de: ['Auf Unterarme stützen', 'Körper gerade wie ein Brett', 'Bauch und Gesäß anspannen', 'Position halten'],
      en: ['Rest on forearms', 'Body straight like a board', 'Tighten abs and glutes', 'Hold position'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 5,
  },
  {
    id: 'bicycle-crunch',
    name: { pl: 'Brzuszki rowerowe', de: 'Fahrrad-Crunches', en: 'Bicycle Crunches' },
    description: {
      pl: 'Skręty z uniesieniem nóg — intensywna praca skośnych mięśni brzucha.',
      de: 'Drehungen mit angehobenen Beinen — intensive schräge Bauchmuskelarbeit.',
      en: 'Twisting with raised legs — intense oblique work.',
    },
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'obliques'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na plecach', 'Ręce za głową', 'Łokieć do przeciwnego kolana', 'Naprzemienne ruchy nóg'],
      de: ['Auf den Rücken legen', 'Hände hinter den Kopf', 'Ellbogen zum gegenüberliegenden Knie', 'Abwechselnde Beinbewegungen'],
      en: ['Lie on your back', 'Hands behind head', 'Elbow to opposite knee', 'Alternating leg movements'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 7,
  },

  // === KARDIO ===
  {
    id: 'burpee',
    name: { pl: 'Burpees', de: 'Burpees', en: 'Burpees' },
    description: {
      pl: 'Kompleksowe ćwiczenie całego ciała — kardio + siła.',
      de: 'Komplexe Ganzkörperübung — Kardio + Kraft.',
      en: 'Complex full-body exercise — cardio + strength.',
    },
    category: 'cardio',
    difficulty: 'advanced',
    muscleGroups: ['full body'],
    equipment: [],
    instructions: {
      pl: ['Przysiad → ręce na podłogę', 'Wyrzuć nogi do tyłu (pozycja pompki)', 'Pompka', 'Podciągnij nogi i wyskocz w górę'],
      de: ['Kniebeuge → Hände auf den Boden', 'Beine nach hinten werfen (Liegestützposition)', 'Liegestütz', 'Beine anziehen und nach oben springen'],
      en: ['Squat → hands on floor', 'Jump feet back (plank position)', 'Push-up', 'Jump feet in and jump up'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 12,
  },
  {
    id: 'jumping-jack',
    name: { pl: 'Pajacyki', de: 'Hampelmänner', en: 'Jumping Jacks' },
    description: {
      pl: 'Klasyczne pajacyki — rozgrzewka i kardio.',
      de: 'Klassische Hampelmänner — Aufwärmung und Kardio.',
      en: 'Classic jumping jacks — warm-up and cardio.',
    },
    category: 'cardio',
    difficulty: 'beginner',
    muscleGroups: ['full body'],
    equipment: [],
    instructions: {
      pl: ['Stój prosto, ręce wzdłuż ciała', 'Wyskocz rozkładając nogi i ręce', 'Wróć do pozycji wyjściowej', 'Powtarzaj dynamicznie'],
      de: ['Gerade stehen, Arme am Körper', 'Springen mit Beinen und Armen auseinander', 'Zurück in Ausgangsposition', 'Dynamisch wiederholen'],
      en: ['Stand straight, arms at sides', 'Jump spreading legs and arms', 'Return to starting position', 'Repeat dynamically'],
    },
    durationSeconds: 60,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 8,
  },
  {
    id: 'mountain-climber',
    name: { pl: 'Wspinaczka górska', de: 'Bergsteiger', en: 'Mountain Climbers' },
    description: {
      pl: 'Dynamiczne podciąganie kolan w pozycji pompki — kardio + core.',
      de: 'Dynamisches Knieanziehen in Liegestützposition — Kardio + Core.',
      en: 'Dynamic knee drives in plank position — cardio + core.',
    },
    category: 'cardio',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'shoulders', 'quads'],
    equipment: [],
    instructions: {
      pl: ['Pozycja pompki', 'Podciągnij kolano do klatki', 'Zmień nogę dynamicznie', 'Utrzymuj szybkie tempo'],
      de: ['Liegestützposition', 'Knie zur Brust ziehen', 'Dynamisch Bein wechseln', 'Schnelles Tempo halten'],
      en: ['Plank position', 'Drive knee to chest', 'Switch legs dynamically', 'Keep fast pace'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 11,
  },

  // === ROZCIĄGANIE ===
  {
    id: 'standing-quad-stretch',
    name: { pl: 'Rozciąganie czworogłowego', de: 'Quadrizeps-Dehnung', en: 'Standing Quad Stretch' },
    description: {
      pl: 'Rozciąganie przedniego uda w pozycji stojącej.',
      de: 'Dehnung des vorderen Oberschenkels im Stehen.',
      en: 'Standing front thigh stretch.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['quads'],
    equipment: [],
    instructions: {
      pl: ['Stań na jednej nodze', 'Chwyć stopę drugiej nogi za plecami', 'Przyciągnij piętę do pośladka', 'Przytrzymaj 20-30 sekund'],
      de: ['Auf einem Bein stehen', 'Fuß des anderen Beins hinter dem Rücken greifen', 'Ferse zum Gesäß ziehen', '20-30 Sekunden halten'],
      en: ['Stand on one leg', 'Grab foot of other leg behind back', 'Pull heel to glute', 'Hold 20-30 seconds'],
    },
    durationSeconds: 30,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },
  {
    id: 'childs-pose',
    name: { pl: 'Pozycja dziecka', de: 'Kindeshaltung', en: 'Child\'s Pose' },
    description: {
      pl: 'Pozycja relaksacyjna rozciągająca plecy i ramiona.',
      de: 'Entspannungsposition für Rücken und Schultern.',
      en: 'Relaxation pose stretching back and shoulders.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['back', 'shoulders', 'hips'],
    equipment: [],
    instructions: {
      pl: ['Uklęknij i usiądź na piętach', 'Wyciągnij ręce do przodu', 'Czoło na podłodze', 'Oddychaj głęboko, przytrzymaj 30-60s'],
      de: ['Knien und auf die Fersen setzen', 'Arme nach vorne strecken', 'Stirn auf den Boden', 'Tief atmen, 30-60s halten'],
      en: ['Kneel and sit on heels', 'Extend arms forward', 'Forehead on floor', 'Breathe deeply, hold 30-60s'],
    },
    durationSeconds: 45,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },

  // === DODATKOWE ĆWICZENIA ===

  // Klatka piersiowa
  {
    id: 'wide-push-up',
    name: { pl: 'Pompki szerokie', de: 'Breite Liegestütze', en: 'Wide Push-ups' },
    description: {
      pl: 'Pompki z szerokim rozstawieniem rąk — nacisk na zewnętrzną część klatki.',
      de: 'Liegestütze mit breitem Griff — Fokus auf äußere Brust.',
      en: 'Wide grip push-ups — emphasis on outer chest.',
    },
    category: 'chest',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'shoulders'],
    equipment: [],
    instructions: {
      pl: ['Ręce szerzej niż barki', 'Ciało proste', 'Opuść klatkę do podłogi', 'Wypchnij się'],
      de: ['Hände breiter als Schultern', 'Körper gerade', 'Brust zum Boden', 'Hochdrücken'],
      en: ['Hands wider than shoulders', 'Body straight', 'Lower chest to floor', 'Push up'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 7,
  },
  {
    id: 'decline-push-up',
    name: { pl: 'Pompki z nogami wyżej', de: 'Decline-Liegestütze', en: 'Decline Push-ups' },
    description: {
      pl: 'Pompki z nogami na podwyższeniu — większe obciążenie górnej klatki.',
      de: 'Liegestütze mit erhöhten Füßen — mehr Belastung für die obere Brust.',
      en: 'Push-ups with elevated feet — greater upper chest load.',
    },
    category: 'chest',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: ['bench'],
    instructions: {
      pl: ['Postaw nogi na podwyższeniu', 'Ręce na podłodze na szerokość barków', 'Opuść klatkę', 'Wypchnij dynamicznie'],
      de: ['Füße auf Erhöhung stellen', 'Hände schulterbreit auf dem Boden', 'Brust senken', 'Dynamisch drücken'],
      en: ['Place feet on elevation', 'Hands shoulder-width on floor', 'Lower chest', 'Push dynamically'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 8,
  },

  // Nogi
  {
    id: 'wall-sit',
    name: { pl: 'Krzesełko', de: 'Wandsitzen', en: 'Wall Sit' },
    description: {
      pl: 'Izometryczne ćwiczenie na nogi — opieranie się o ścianę w pozycji krzesła.',
      de: 'Isometrische Beinübung — an der Wand in Stuhlposition sitzen.',
      en: 'Isometric leg exercise — sitting against wall in chair position.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes'],
    equipment: [],
    instructions: {
      pl: ['Oprzyj plecy o ścianę', 'Zejdź do kąta 90° w kolanach', 'Utrzymaj pozycję', 'Oddychaj równomiernie'],
      de: ['Rücken an die Wand lehnen', 'Auf 90° in den Knien senken', 'Position halten', 'Gleichmäßig atmen'],
      en: ['Lean back against wall', 'Lower to 90° knee angle', 'Hold position', 'Breathe evenly'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 5,
  },
  {
    id: 'calf-raise',
    name: { pl: 'Wspięcia na palce', de: 'Wadenheben', en: 'Calf Raises' },
    description: {
      pl: 'Wspięcia na palce stóp — izolacja mięśni łydek.',
      de: 'Auf die Zehenspitzen heben — Isolation der Wadenmuskulatur.',
      en: 'Rising on toes — calf muscle isolation.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['calves'],
    equipment: [],
    instructions: {
      pl: ['Stań prosto', 'Unieś się na palce', 'Przytrzymaj 1-2s na górze', 'Opuść powoli'],
      de: ['Gerade stehen', 'Auf Zehenspitzen heben', '1-2s oben halten', 'Langsam absenken'],
      en: ['Stand straight', 'Rise on toes', 'Hold 1-2s at top', 'Lower slowly'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 4,
  },
  {
    id: 'glute-bridge',
    name: { pl: 'Mostek', de: 'Glute Bridge', en: 'Glute Bridge' },
    description: {
      pl: 'Unoszenie bioder w leżeniu — wzmacnia pośladki i tylną część ud.',
      de: 'Hüften im Liegen heben — stärkt Gesäß und hintere Oberschenkel.',
      en: 'Hip raise while lying — strengthens glutes and hamstrings.',
    },
    category: 'legs',
    difficulty: 'beginner',
    muscleGroups: ['glutes', 'hamstrings', 'lower back'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na plecach', 'Kolana ugięte, stopy na podłodze', 'Unieś biodra wysoko', 'Ściśnij pośladki na górze'],
      de: ['Auf den Rücken legen', 'Knie gebeugt, Füße auf dem Boden', 'Hüften hoch heben', 'Gesäß oben anspannen'],
      en: ['Lie on back', 'Knees bent, feet on floor', 'Raise hips high', 'Squeeze glutes at top'],
    },
    reps: 15,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 5,
  },

  // Brzuch
  {
    id: 'leg-raise',
    name: { pl: 'Unoszenie nóg', de: 'Beinheben', en: 'Leg Raises' },
    description: {
      pl: 'Unoszenie prostych nóg w leżeniu — intensywna praca dolnych mięśni brzucha.',
      de: 'Gestrecktes Beinheben im Liegen — intensive untere Bauchmuskelarbeit.',
      en: 'Lying leg raises — intense lower ab work.',
    },
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'hip flexors'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na plecach', 'Nogi proste, ręce wzdłuż ciała', 'Unieś nogi do 90°', 'Opuść powoli, nie dotykając podłogi'],
      de: ['Auf den Rücken legen', 'Beine gestreckt, Arme am Körper', 'Beine auf 90° heben', 'Langsam senken, nicht den Boden berühren'],
      en: ['Lie on back', 'Legs straight, arms at sides', 'Raise legs to 90°', 'Lower slowly without touching floor'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 6,
  },
  {
    id: 'russian-twist',
    name: { pl: 'Skręty rosyjskie', de: 'Russian Twist', en: 'Russian Twist' },
    description: {
      pl: 'Skręty tułowia z uniesionym plecami — praca mięśni skośnych.',
      de: 'Rumpfdrehungen mit angehobenen Schultern — Training der schrägen Bauchmuskeln.',
      en: 'Torso rotations with raised back — oblique work.',
    },
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'obliques'],
    equipment: [],
    instructions: {
      pl: ['Usiądź z ugiętymi kolanami', 'Odchyl tułów do tyłu ~45°', 'Skręcaj tułów na boki', 'Dotykaj podłogi rękami naprzemiennie'],
      de: ['Mit gebeugten Knien setzen', 'Oberkörper ~45° nach hinten neigen', 'Rumpf zu den Seiten drehen', 'Abwechselnd den Boden berühren'],
      en: ['Sit with bent knees', 'Lean torso back ~45°', 'Rotate torso side to side', 'Touch floor alternately with hands'],
    },
    reps: 20,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 7,
  },
  {
    id: 'side-plank',
    name: { pl: 'Plank boczny', de: 'Seitlicher Plank', en: 'Side Plank' },
    description: {
      pl: 'Izometryczne ćwiczenie na mięśnie skośne i stabilizację.',
      de: 'Isometrische Übung für schräge Bauchmuskeln und Stabilisation.',
      en: 'Isometric exercise for obliques and stabilization.',
    },
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ['obliques', 'core', 'shoulders'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na boku', 'Oprzyj się na przedramieniu', 'Unieś biodra — ciało proste', 'Utrzymaj po 30s na każdą stronę'],
      de: ['Auf die Seite legen', 'Auf Unterarm stützen', 'Hüften heben — Körper gerade', '30s pro Seite halten'],
      en: ['Lie on side', 'Support on forearm', 'Raise hips — body straight', 'Hold 30s each side'],
    },
    durationSeconds: 30,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 5,
  },

  // Kardio
  {
    id: 'high-knees',
    name: { pl: 'Kolana w górę', de: 'Knieheben', en: 'High Knees' },
    description: {
      pl: 'Bieg w miejscu z wysokim unoszeniem kolan — intensywne kardio.',
      de: 'Laufen auf der Stelle mit hohem Knieheben — intensives Kardio.',
      en: 'Running in place with high knee raises — intense cardio.',
    },
    category: 'cardio',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'core', 'calves'],
    equipment: [],
    instructions: {
      pl: ['Biegnij w miejscu', 'Unoś kolana powyżej bioder', 'Pracuj ramionami', 'Utrzymaj szybkie tempo'],
      de: ['Auf der Stelle laufen', 'Knie über die Hüften heben', 'Arme mitbewegen', 'Schnelles Tempo halten'],
      en: ['Run in place', 'Raise knees above hips', 'Pump arms', 'Keep fast pace'],
    },
    durationSeconds: 45,
    sets: 3,
    restSeconds: 30,
    caloriesPerMinute: 10,
  },
  {
    id: 'squat-jump-180',
    name: { pl: 'Przysiad z obrotem 180°', de: '180° Sprung-Kniebeuge', en: '180° Jump Squat' },
    description: {
      pl: 'Przysiad z wyskokiem i obrotem o 180 stopni — siła eksplozywna + koordynacja.',
      de: 'Kniebeuge mit Sprung und 180°-Drehung — Explosivkraft + Koordination.',
      en: 'Squat with jump and 180° turn — explosive power + coordination.',
    },
    category: 'cardio',
    difficulty: 'advanced',
    muscleGroups: ['quads', 'glutes', 'core', 'calves'],
    equipment: [],
    instructions: {
      pl: ['Wykonaj przysiad', 'Wyskocz i obróć się o 180°', 'Ląduj miękko w przysiadzie', 'Powtórz w drugą stronę'],
      de: ['Kniebeuge ausführen', 'Springen und 180° drehen', 'Weich in Kniebeuge landen', 'In andere Richtung wiederholen'],
      en: ['Perform squat', 'Jump and rotate 180°', 'Land softly in squat', 'Repeat other direction'],
    },
    reps: 10,
    sets: 3,
    restSeconds: 60,
    caloriesPerMinute: 12,
  },

  // Plecy
  {
    id: 'reverse-snow-angel',
    name: { pl: 'Odwrócony śnieżny anioł', de: 'Umgekehrter Schnee-Engel', en: 'Reverse Snow Angel' },
    description: {
      pl: 'Ruch ramion w leżeniu na brzuchu — wzmacnia górne plecy i łopatki.',
      de: 'Armbewegung in Bauchlage — stärkt oberen Rücken und Schulterblätter.',
      en: 'Arm movement lying face down — strengthens upper back and scapulae.',
    },
    category: 'back',
    difficulty: 'beginner',
    muscleGroups: ['upper back', 'rear delts', 'lower back'],
    equipment: [],
    instructions: {
      pl: ['Połóż się na brzuchu', 'Ręce wyciągnięte nad głową', 'Unieś ręce i zataczaj łuk do bioder', 'Wróć do pozycji wyjściowej'],
      de: ['Auf den Bauch legen', 'Arme über den Kopf strecken', 'Arme heben und Bogen zu den Hüften', 'Zurück in Ausgangsposition'],
      en: ['Lie face down', 'Arms extended overhead', 'Raise arms and arc to hips', 'Return to start'],
    },
    reps: 12,
    sets: 3,
    restSeconds: 45,
    caloriesPerMinute: 4,
  },

  // Rozciąganie
  {
    id: 'hamstring-stretch',
    name: { pl: 'Rozciąganie dwugłowego', de: 'Oberschenkeldehnung', en: 'Hamstring Stretch' },
    description: {
      pl: 'Rozciąganie tylnej części uda w pozycji siedzącej.',
      de: 'Dehnung der hinteren Oberschenkelmuskulatur im Sitzen.',
      en: 'Seated hamstring stretch.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['hamstrings', 'lower back'],
    equipment: [],
    instructions: {
      pl: ['Usiądź z wyprostowaną nogą', 'Drugą nogę ugięta, stopa przy udzie', 'Pochyl się do przodu', 'Przytrzymaj 20-30s, zmień stronę'],
      de: ['Mit gestrecktem Bein setzen', 'Anderes Bein gebeugt, Fuß am Oberschenkel', 'Nach vorne beugen', '20-30s halten, Seite wechseln'],
      en: ['Sit with extended leg', 'Other leg bent, foot at thigh', 'Lean forward', 'Hold 20-30s, switch sides'],
    },
    durationSeconds: 30,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },
  {
    id: 'cat-cow',
    name: { pl: 'Kot-krowa', de: 'Katze-Kuh', en: 'Cat-Cow' },
    description: {
      pl: 'Naprzemienne wyginanie i zaokrąglanie kręgosłupa — mobilność pleców.',
      de: 'Abwechselndes Strecken und Runden der Wirbelsäule — Rückenmobilität.',
      en: 'Alternating spine extension and flexion — back mobility.',
    },
    category: 'stretching',
    difficulty: 'beginner',
    muscleGroups: ['back', 'core'],
    equipment: [],
    instructions: {
      pl: ['Klęknij na czworakach', 'Wdech — wygnij plecy w dół (krowa)', 'Wydech — zaokrąglij plecy w górę (kot)', 'Powtarzaj płynnie'],
      de: ['Auf allen Vieren knien', 'Einatmen — Rücken nach unten biegen (Kuh)', 'Ausatmen — Rücken nach oben runden (Katze)', 'Fließend wiederholen'],
      en: ['Kneel on all fours', 'Inhale — arch back down (cow)', 'Exhale — round back up (cat)', 'Repeat smoothly'],
    },
    durationSeconds: 60,
    sets: 2,
    restSeconds: 10,
    caloriesPerMinute: 2,
  },
];
